// packages/content/scripts/build-postal-code-names.ts
//
// Builds the postal code → town name table shown under the quote form's postal code field.
// Run from packages/content:
//   node --experimental-strip-types scripts/build-postal-code-names.ts
//
// Input : data-raw/ES.txt (GeoNames postal codes, CC BY 4.0; see docs/zonas-cp.md for download)
// Output: src/data/postal-code-names.ts
//
// Owner rules (2026-10-07): one name per postal code — the main town, not every hamlet sharing
// the code — and only the first form of a bilingual name («Alicante/Alacant» → «Alicante»).
// Small GeoNames imperfections (a missing accent, odd capitalisation) are accepted as they come.

import { readFileSync, statSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

type Row = { place: string; municipality: string; accuracy: number }

const ROOT = resolve(import.meta.dirname, '..')
const SOURCE_FILE = resolve(ROOT, 'data-raw/ES.txt')
const OUT_DATA = resolve(ROOT, 'src/data/postal-code-names.ts')
const POSTAL_CODE_REGEX = /^\d{5}$/
const PROVINCE_PREFIX_LENGTH = 2

const normalize = (s: string) => s.normalize('NFD').replace(/\p{Diacritic}/gu, '').toLowerCase().trim()

// «Pobla Tornesa, la» → «La Pobla Tornesa»; «Alcora, l'» → «L'Alcora».
function moveArticle(name: string): string {
  const match = /^(.*), (la|el|les|els|los|las|l')$/i.exec(name)
  if (!match) return name
  const article = match[2].charAt(0).toUpperCase() + match[2].slice(1).toLowerCase()
  return article.endsWith("'") ? `${article}${match[1]}` : `${article} ${match[1]}`
}

/** First form of a bilingual name, article moved to the front. */
const firstForm = (name: string) => moveArticle(name.split('/')[0].trim())

/**
 * The main town of a postal code. When a locality's name matches its municipality, the
 * municipality's spelling wins (GeoNames writes it with accents: «Castellón de la Plana» rather
 * than «Castellon De La Plana»). Otherwise, the most accurate locality, in source order.
 */
function mainName(rows: Row[]): string {
  for (const row of rows) {
    if (!row.municipality) continue
    const variants = row.municipality.split('/').map((v) => normalize(moveArticle(v.trim())))
    const places = row.place.split('/').map((p) => normalize(p))
    if (places.some((p) => variants.includes(p))) return firstForm(row.municipality)
  }
  const best = Math.max(...rows.map((r) => r.accuracy))
  return firstForm(rows.find((r) => r.accuracy === best)!.place)
}

const byPostalCode = new Map<string, Row[]>()
for (const line of readFileSync(SOURCE_FILE, 'utf8').split('\n')) {
  const f = line.split('\t')
  const postalCode = f[1]
  if (!postalCode || !POSTAL_CODE_REGEX.test(postalCode)) continue
  const row: Row = { place: f[2] ?? '', municipality: f[7] ?? '', accuracy: Number(f[11]) || 0 }
  byPostalCode.set(postalCode, [...(byPostalCode.get(postalCode) ?? []), row])
}

// Grouped by province prefix: the public route serves one province at a time.
const byProvince = new Map<string, [string, string][]>()
for (const postalCode of [...byPostalCode.keys()].sort()) {
  const prefix = postalCode.slice(0, PROVINCE_PREFIX_LENGTH)
  const entry: [string, string] = [postalCode.slice(PROVINCE_PREFIX_LENGTH), mainName(byPostalCode.get(postalCode)!)]
  byProvince.set(prefix, [...(byProvince.get(prefix) ?? []), entry])
}

const downloadDate = statSync(SOURCE_FILE).mtime.toISOString().slice(0, 10)
const body = [...byProvince.entries()]
  .map(([prefix, entries]) => `  '${prefix}': {\n${entries.map(([suffix, name]) => `    '${suffix}': ${JSON.stringify(name)},`).join('\n')}\n  },`)
  .join('\n')

writeFileSync(
  OUT_DATA,
  `// generated by build-postal-code-names.ts, do not edit
// Source: GeoNames postal codes (© GeoNames, CC BY 4.0), downloaded ${downloadDate}.

/**
 * Main town name per Spanish postal code, grouped by province prefix (first two digits) and
 * keyed by the remaining three. ${byPostalCode.size} postal codes in ${byProvince.size} provinces.
 * Not exhaustive: Correos publishes no open list, so a real postal code may be missing here.
 */
export const POSTAL_CODE_NAMES: Readonly<Record<string, Readonly<Record<string, string>>>> = {
${body}
}
`,
)

console.log(`Postal codes: ${byPostalCode.size} | provinces: ${byProvince.size}`)
