/**
 * Lead routing: which quote requests the business accepts, by postal code and surface.
 *
 * Server-only. `data/lead-zones.ts` carries ~450 postal codes; nothing a `'use client'`
 * component imports may reach this module (the Server Action that uses it is fine: a client
 * component only receives a reference to the action, never its code).
 *
 * The thresholds and prefixes live in `data/lead-zones.ts`, generated by
 * `scripts/build-lead-zones.ts` — see `docs/zonas-cp.md` for how the zones were drawn.
 */
import {
  VALID_PROVINCE_RANGE,
  ZONE_A_POSTAL_CODES,
  ZONE_B_MIN_M2,
  ZONE_B_PREFIXES,
  ZONE_C_MIN_M2,
} from '../data/lead-zones.ts'

/** A: near Sollana, any surface. B: rest of the Comunitat Valenciana. C: rest of Spain. */
export type LeadZone = 'A' | 'B' | 'C' | 'unknown'

export type LeadClassification = {
  zone: LeadZone
  /** Whether the request clears its zone's minimum surface. Doubtful input is accepted. */
  accepted: boolean
  /** Surface the request must exceed in its zone; `null` when any surface is accepted. */
  minSquareMeters: number | null
}

const POSTAL_CODE_REGEX = /^\d{5}$/
const PROVINCE_PREFIX_LENGTH = 2

const zoneAPostalCodes = new Set(ZONE_A_POSTAL_CODES)
const zoneBPrefixes = new Set<string>(ZONE_B_PREFIXES)

/** Spaces are the only thing stripped: a postal code typed as `46 440` is still `46440`. */
export function normalizePostalCode(raw: string): string {
  return raw.replace(/\s/g, '')
}

export function isValidPostalCode(raw: string): boolean {
  const postalCode = normalizePostalCode(raw)
  if (!POSTAL_CODE_REGEX.test(postalCode)) return false
  const province = Number(postalCode.slice(0, PROVINCE_PREFIX_LENGTH))
  return province >= VALID_PROVINCE_RANGE.min && province <= VALID_PROVINCE_RANGE.max
}

function zoneOf(postalCode: string): LeadZone {
  if (!isValidPostalCode(postalCode)) return 'unknown'
  const normalized = normalizePostalCode(postalCode)
  if (zoneAPostalCodes.has(normalized)) return 'A'
  if (zoneBPrefixes.has(normalized.slice(0, PROVINCE_PREFIX_LENGTH))) return 'B'
  return 'C'
}

/**
 * Owner rules (2026-10-07): Zone A accepts anything; Zone B only more than `ZONE_B_MIN_M2`;
 * Zone C only more than `ZONE_C_MIN_M2` — strictly more, so exactly 500 in B is not accepted.
 * An unknown postal code or a missing surface is accepted: when in doubt, the lead is not lost.
 */
export function classifyLead({
  postalCode,
  squareMeters,
}: {
  postalCode: string
  squareMeters: number | null
}): LeadClassification {
  const zone = zoneOf(postalCode)
  const minSquareMeters = zone === 'B' ? ZONE_B_MIN_M2 : zone === 'C' ? ZONE_C_MIN_M2 : null
  const accepted = minSquareMeters === null || squareMeters === null || squareMeters > minSquareMeters
  return { zone, accepted, minSquareMeters }
}

// `120`, `120,5`, `1.200` (Spanish thousands separator), with an optional unit after it.
const NUMBER = String.raw`\d+(?:[.,]\d+)*`
const UNIT = String.raw`(?:m2|m²|mts?2?|metros?(?:\s+cuadrados?)?)?`
const SINGLE_REGEX = new RegExp(String.raw`^(${NUMBER})\s*${UNIT}$`, 'i')
// `10x5`, `10 × 5`, `10*5`: the form's help text asks for «Largo × ancho».
const PRODUCT_REGEX = new RegExp(String.raw`^(${NUMBER})\s*[x×*]\s*(${NUMBER})\s*${UNIT}$`, 'i')
const THOUSANDS_REGEX = /^\d{1,3}(?:\.\d{3})+$/

function toNumber(raw: string): number {
  // `1.200` is twelve hundred in Spanish; `1.5` and `1,5` are one and a half.
  const plain = THOUSANDS_REGEX.test(raw) ? raw.replace(/\./g, '') : raw.replace(',', '.')
  return Number(plain)
}

/**
 * The surface the visitor typed, in m², or `null` when it can't be read with confidence.
 * Deliberately conservative: «unos 80» or «no sé» return `null`, and the form asks again
 * instead of guessing a number that would decide where the lead goes.
 */
export function parseSquareMeters(raw: string): number | null {
  const text = raw.trim().replace(/\s+/g, ' ')
  const product = PRODUCT_REGEX.exec(text)
  const single = product ? null : SINGLE_REGEX.exec(text)
  const value = product ? toNumber(product[1]) * toNumber(product[2]) : single ? toNumber(single[1]) : NaN
  return Number.isFinite(value) && value > 0 ? value : null
}
