/**
 * Town name for a Spanish postal code, from `data/postal-code-names.ts` (GeoNames, generated by
 * `scripts/build-postal-code-names.ts`).
 *
 * Server-only: the table carries ~11,000 names. The browser never imports it — it fetches one
 * province at a time from the static route `apps/web/src/app/api/cp/[provincia]/route.ts`.
 */
import { POSTAL_CODE_NAMES } from '../data/postal-code-names.ts'

const POSTAL_CODE_REGEX = /^\d{5}$/
const PROVINCE_PREFIX_LENGTH = 2

/** Every province prefix in the table (`'01'`…`'52'`). */
export function getPostalCodeProvinces(): string[] {
  return Object.keys(POSTAL_CODE_NAMES)
}

/** One province's names, keyed by the last three digits; `undefined` for an unknown prefix. */
export function getProvincePostalCodeNames(prefix: string): Readonly<Record<string, string>> | undefined {
  return Object.hasOwn(POSTAL_CODE_NAMES, prefix) ? POSTAL_CODE_NAMES[prefix] : undefined
}

/** `undefined` when the code is malformed or missing from the table — which does not make it invalid. */
export function getPostalCodeName(postalCode: string): string | undefined {
  const code = postalCode.replace(/\s/g, '')
  if (!POSTAL_CODE_REGEX.test(code)) return undefined
  const province = getProvincePostalCodeNames(code.slice(0, PROVINCE_PREFIX_LENGTH))
  const suffix = code.slice(PROVINCE_PREFIX_LENGTH)
  return province && Object.hasOwn(province, suffix) ? province[suffix] : undefined
}
